// Lista global de países com código ISO 3166-1 alpha-2, indicativo telefónico
// internacional e nome em português europeu (pt-PT).
//
// Usada nos formulários públicos (país de residência + prefixo telefónico) e
// partilhável com a área de administração. A bandeira é derivada do código ISO,
// pelo que só é necessário manter nome + dialCode aqui.

export interface Country {
  /** Código ISO 3166-1 alpha-2 (ex.: 'PT'). */
  code: string;
  /** Nome do país em português europeu. */
  name: string;
  /** Indicativo telefónico internacional, sem o '+' (ex.: '351'). */
  dial: string;
}

export const COUNTRIES: Country[] = [
  { code: 'AF', name: 'Afeganistão', dial: '93' },
  { code: 'ZA', name: 'África do Sul', dial: '27' },
  { code: 'AL', name: 'Albânia', dial: '355' },
  { code: 'DE', name: 'Alemanha', dial: '49' },
  { code: 'AD', name: 'Andorra', dial: '376' },
  { code: 'AO', name: 'Angola', dial: '244' },
  { code: 'AI', name: 'Anguila', dial: '1264' },
  { code: 'AG', name: 'Antígua e Barbuda', dial: '1268' },
  { code: 'SA', name: 'Arábia Saudita', dial: '966' },
  { code: 'DZ', name: 'Argélia', dial: '213' },
  { code: 'AR', name: 'Argentina', dial: '54' },
  { code: 'AM', name: 'Arménia', dial: '374' },
  { code: 'AW', name: 'Aruba', dial: '297' },
  { code: 'AU', name: 'Austrália', dial: '61' },
  { code: 'AT', name: 'Áustria', dial: '43' },
  { code: 'AZ', name: 'Azerbaijão', dial: '994' },
  { code: 'BS', name: 'Baamas', dial: '1242' },
  { code: 'BD', name: 'Bangladeche', dial: '880' },
  { code: 'BB', name: 'Barbados', dial: '1246' },
  { code: 'BH', name: 'Barém', dial: '973' },
  { code: 'BE', name: 'Bélgica', dial: '32' },
  { code: 'BZ', name: 'Belize', dial: '501' },
  { code: 'BJ', name: 'Benim', dial: '229' },
  { code: 'BM', name: 'Bermudas', dial: '1441' },
  { code: 'BY', name: 'Bielorrússia', dial: '375' },
  { code: 'BO', name: 'Bolívia', dial: '591' },
  { code: 'BA', name: 'Bósnia e Herzegovina', dial: '387' },
  { code: 'BW', name: 'Botsuana', dial: '267' },
  { code: 'BR', name: 'Brasil', dial: '55' },
  { code: 'BN', name: 'Brunei', dial: '673' },
  { code: 'BG', name: 'Bulgária', dial: '359' },
  { code: 'BF', name: 'Burquina Faso', dial: '226' },
  { code: 'BI', name: 'Burúndi', dial: '257' },
  { code: 'BT', name: 'Butão', dial: '975' },
  { code: 'CV', name: 'Cabo Verde', dial: '238' },
  { code: 'CM', name: 'Camarões', dial: '237' },
  { code: 'KH', name: 'Camboja', dial: '855' },
  { code: 'CA', name: 'Canadá', dial: '1' },
  { code: 'QA', name: 'Catar', dial: '974' },
  { code: 'KZ', name: 'Cazaquistão', dial: '7' },
  { code: 'TD', name: 'Chade', dial: '235' },
  { code: 'CL', name: 'Chile', dial: '56' },
  { code: 'CN', name: 'China', dial: '86' },
  { code: 'CY', name: 'Chipre', dial: '357' },
  { code: 'CO', name: 'Colômbia', dial: '57' },
  { code: 'KM', name: 'Comores', dial: '269' },
  { code: 'CG', name: 'Congo', dial: '242' },
  { code: 'CD', name: 'Congo (República Democrática)', dial: '243' },
  { code: 'KP', name: 'Coreia do Norte', dial: '850' },
  { code: 'KR', name: 'Coreia do Sul', dial: '82' },
  { code: 'CI', name: 'Costa do Marfim', dial: '225' },
  { code: 'CR', name: 'Costa Rica', dial: '506' },
  { code: 'HR', name: 'Croácia', dial: '385' },
  { code: 'CU', name: 'Cuba', dial: '53' },
  { code: 'CW', name: 'Curaçau', dial: '599' },
  { code: 'DK', name: 'Dinamarca', dial: '45' },
  { code: 'DJ', name: 'Jibuti', dial: '253' },
  { code: 'DM', name: 'Domínica', dial: '1767' },
  { code: 'EG', name: 'Egito', dial: '20' },
  { code: 'SV', name: 'Salvador', dial: '503' },
  { code: 'AE', name: 'Emirados Árabes Unidos', dial: '971' },
  { code: 'EC', name: 'Equador', dial: '593' },
  { code: 'ER', name: 'Eritreia', dial: '291' },
  { code: 'SK', name: 'Eslováquia', dial: '421' },
  { code: 'SI', name: 'Eslovénia', dial: '386' },
  { code: 'ES', name: 'Espanha', dial: '34' },
  { code: 'US', name: 'Estados Unidos', dial: '1' },
  { code: 'EE', name: 'Estónia', dial: '372' },
  { code: 'SZ', name: 'Essuatíni', dial: '268' },
  { code: 'ET', name: 'Etiópia', dial: '251' },
  { code: 'FJ', name: 'Fiji', dial: '679' },
  { code: 'PH', name: 'Filipinas', dial: '63' },
  { code: 'FI', name: 'Finlândia', dial: '358' },
  { code: 'FR', name: 'França', dial: '33' },
  { code: 'GA', name: 'Gabão', dial: '241' },
  { code: 'GM', name: 'Gâmbia', dial: '220' },
  { code: 'GH', name: 'Gana', dial: '233' },
  { code: 'GE', name: 'Geórgia', dial: '995' },
  { code: 'GI', name: 'Gibraltar', dial: '350' },
  { code: 'GD', name: 'Granada', dial: '1473' },
  { code: 'GR', name: 'Grécia', dial: '30' },
  { code: 'GL', name: 'Gronelândia', dial: '299' },
  { code: 'GP', name: 'Guadalupe', dial: '590' },
  { code: 'GU', name: 'Guam', dial: '1671' },
  { code: 'GT', name: 'Guatemala', dial: '502' },
  { code: 'GG', name: 'Guernsey', dial: '44' },
  { code: 'GY', name: 'Guiana', dial: '592' },
  { code: 'GF', name: 'Guiana Francesa', dial: '594' },
  { code: 'GN', name: 'Guiné', dial: '224' },
  { code: 'GW', name: 'Guiné-Bissau', dial: '245' },
  { code: 'GQ', name: 'Guiné Equatorial', dial: '240' },
  { code: 'HT', name: 'Haiti', dial: '509' },
  { code: 'NL', name: 'Países Baixos', dial: '31' },
  { code: 'HN', name: 'Honduras', dial: '504' },
  { code: 'HK', name: 'Hong Kong', dial: '852' },
  { code: 'HU', name: 'Hungria', dial: '36' },
  { code: 'YE', name: 'Iémen', dial: '967' },
  { code: 'IN', name: 'Índia', dial: '91' },
  { code: 'ID', name: 'Indonésia', dial: '62' },
  { code: 'IR', name: 'Irão', dial: '98' },
  { code: 'IQ', name: 'Iraque', dial: '964' },
  { code: 'IE', name: 'Irlanda', dial: '353' },
  { code: 'IS', name: 'Islândia', dial: '354' },
  { code: 'IL', name: 'Israel', dial: '972' },
  { code: 'IT', name: 'Itália', dial: '39' },
  { code: 'JM', name: 'Jamaica', dial: '1876' },
  { code: 'JP', name: 'Japão', dial: '81' },
  { code: 'JE', name: 'Jersey', dial: '44' },
  { code: 'JO', name: 'Jordânia', dial: '962' },
  { code: 'KW', name: 'Kuwait', dial: '965' },
  { code: 'LA', name: 'Laos', dial: '856' },
  { code: 'LS', name: 'Lesoto', dial: '266' },
  { code: 'LV', name: 'Letónia', dial: '371' },
  { code: 'LB', name: 'Líbano', dial: '961' },
  { code: 'LR', name: 'Libéria', dial: '231' },
  { code: 'LY', name: 'Líbia', dial: '218' },
  { code: 'LI', name: 'Listenstaine', dial: '423' },
  { code: 'LT', name: 'Lituânia', dial: '370' },
  { code: 'LU', name: 'Luxemburgo', dial: '352' },
  { code: 'MO', name: 'Macau', dial: '853' },
  { code: 'MK', name: 'Macedónia do Norte', dial: '389' },
  { code: 'MG', name: 'Madagáscar', dial: '261' },
  { code: 'MY', name: 'Malásia', dial: '60' },
  { code: 'MW', name: 'Maláui', dial: '265' },
  { code: 'MV', name: 'Maldivas', dial: '960' },
  { code: 'ML', name: 'Mali', dial: '223' },
  { code: 'MT', name: 'Malta', dial: '356' },
  { code: 'MA', name: 'Marrocos', dial: '212' },
  { code: 'MQ', name: 'Martinica', dial: '596' },
  { code: 'MU', name: 'Maurícia', dial: '230' },
  { code: 'MR', name: 'Mauritânia', dial: '222' },
  { code: 'MX', name: 'México', dial: '52' },
  { code: 'MM', name: 'Mianmar', dial: '95' },
  { code: 'FM', name: 'Micronésia', dial: '691' },
  { code: 'MZ', name: 'Moçambique', dial: '258' },
  { code: 'MD', name: 'Moldávia', dial: '373' },
  { code: 'MC', name: 'Mónaco', dial: '377' },
  { code: 'MN', name: 'Mongólia', dial: '976' },
  { code: 'ME', name: 'Montenegro', dial: '382' },
  { code: 'MS', name: 'Monserrate', dial: '1664' },
  { code: 'NA', name: 'Namíbia', dial: '264' },
  { code: 'NR', name: 'Nauru', dial: '674' },
  { code: 'NP', name: 'Nepal', dial: '977' },
  { code: 'NI', name: 'Nicarágua', dial: '505' },
  { code: 'NE', name: 'Níger', dial: '227' },
  { code: 'NG', name: 'Nigéria', dial: '234' },
  { code: 'NO', name: 'Noruega', dial: '47' },
  { code: 'NC', name: 'Nova Caledónia', dial: '687' },
  { code: 'NZ', name: 'Nova Zelândia', dial: '64' },
  { code: 'OM', name: 'Omã', dial: '968' },
  { code: 'PW', name: 'Palau', dial: '680' },
  { code: 'PS', name: 'Palestina', dial: '970' },
  { code: 'PA', name: 'Panamá', dial: '507' },
  { code: 'PG', name: 'Papua-Nova Guiné', dial: '675' },
  { code: 'PK', name: 'Paquistão', dial: '92' },
  { code: 'PY', name: 'Paraguai', dial: '595' },
  { code: 'PE', name: 'Peru', dial: '51' },
  { code: 'PF', name: 'Polinésia Francesa', dial: '689' },
  { code: 'PL', name: 'Polónia', dial: '48' },
  { code: 'PR', name: 'Porto Rico', dial: '1787' },
  { code: 'PT', name: 'Portugal', dial: '351' },
  { code: 'KE', name: 'Quénia', dial: '254' },
  { code: 'KG', name: 'Quirguistão', dial: '996' },
  { code: 'KI', name: 'Quiribáti', dial: '686' },
  { code: 'GB', name: 'Reino Unido', dial: '44' },
  { code: 'CF', name: 'República Centro-Africana', dial: '236' },
  { code: 'DO', name: 'República Dominicana', dial: '1809' },
  { code: 'CZ', name: 'República Checa', dial: '420' },
  { code: 'RE', name: 'Reunião', dial: '262' },
  { code: 'RO', name: 'Roménia', dial: '40' },
  { code: 'RW', name: 'Ruanda', dial: '250' },
  { code: 'RU', name: 'Rússia', dial: '7' },
  { code: 'EH', name: 'Sara Ocidental', dial: '212' },
  { code: 'WS', name: 'Samoa', dial: '685' },
  { code: 'AS', name: 'Samoa Americana', dial: '1684' },
  { code: 'SM', name: 'São Marinho', dial: '378' },
  { code: 'ST', name: 'São Tomé e Príncipe', dial: '239' },
  { code: 'SN', name: 'Senegal', dial: '221' },
  { code: 'SL', name: 'Serra Leoa', dial: '232' },
  { code: 'RS', name: 'Sérvia', dial: '381' },
  { code: 'SC', name: 'Seicheles', dial: '248' },
  { code: 'SG', name: 'Singapura', dial: '65' },
  { code: 'SY', name: 'Síria', dial: '963' },
  { code: 'SO', name: 'Somália', dial: '252' },
  { code: 'LK', name: 'Sri Lanca', dial: '94' },
  { code: 'SD', name: 'Sudão', dial: '249' },
  { code: 'SS', name: 'Sudão do Sul', dial: '211' },
  { code: 'SE', name: 'Suécia', dial: '46' },
  { code: 'CH', name: 'Suíça', dial: '41' },
  { code: 'SR', name: 'Suriname', dial: '597' },
  { code: 'TH', name: 'Tailândia', dial: '66' },
  { code: 'TW', name: 'Taiwan', dial: '886' },
  { code: 'TJ', name: 'Tajiquistão', dial: '992' },
  { code: 'TZ', name: 'Tanzânia', dial: '255' },
  { code: 'TL', name: 'Timor-Leste', dial: '670' },
  { code: 'TG', name: 'Togo', dial: '228' },
  { code: 'TO', name: 'Tonga', dial: '676' },
  { code: 'TT', name: 'Trindade e Tobago', dial: '1868' },
  { code: 'TN', name: 'Tunísia', dial: '216' },
  { code: 'TM', name: 'Turquemenistão', dial: '993' },
  { code: 'TR', name: 'Turquia', dial: '90' },
  { code: 'TC', name: 'Turcas e Caicos', dial: '1649' },
  { code: 'UA', name: 'Ucrânia', dial: '380' },
  { code: 'UG', name: 'Uganda', dial: '256' },
  { code: 'UY', name: 'Uruguai', dial: '598' },
  { code: 'UZ', name: 'Usbequistão', dial: '998' },
  { code: 'VU', name: 'Vanuatu', dial: '678' },
  { code: 'VA', name: 'Vaticano', dial: '379' },
  { code: 'VE', name: 'Venezuela', dial: '58' },
  { code: 'VN', name: 'Vietname', dial: '84' },
  { code: 'ZM', name: 'Zâmbia', dial: '260' },
  { code: 'ZW', name: 'Zimbabué', dial: '263' },
];

/** Países ordenados alfabeticamente pelo nome (pt-PT), para listas de seleção. */
export const COUNTRIES_SORTED: Country[] = [...COUNTRIES].sort((a, b) =>
  a.name.localeCompare(b.name, 'pt')
);

const BY_CODE = new Map(COUNTRIES.map((c) => [c.code, c]));

/** Devolve o país pelo código ISO alpha-2, ou undefined. */
export function countryByCode(code: string): Country | undefined {
  return BY_CODE.get(code);
}

/**
 * Bandeira em emoji derivada do código ISO alpha-2 (pares de indicadores
 * regionais Unicode). Devolve '' se o código for inválido.
 */
export function flagEmoji(code: string): string {
  if (!/^[A-Za-z]{2}$/.test(code)) return '';
  const base = 0x1f1e6;
  const chars = code
    .toUpperCase()
    .split('')
    .map((c) => base + (c.charCodeAt(0) - 65));
  return String.fromCodePoint(...chars);
}

/** Indicativo telefónico (com '+') do país indicado, ou '' se desconhecido. */
export function dialCodeOf(code: string): string {
  const c = BY_CODE.get(code);
  return c ? `+${c.dial}` : '';
}
