name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: insjcm
  SERVICE_NAME: caridade-website # Nome do serviço no Cloud Run
  REGION: europe-west1 # Altere se a sua região for diferente

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write' # Necessário para o Workload Identity Federation (WIF)

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      # Autenticação segura usando WIF (Evita chaves de conta de serviço no GitHub Secrets)
      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
          service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'

      # Faz o deploy utilizando o Dockerfile do repositório
      # O deploy-cloudrun suporta "source" nativamente através do Cloud Build
      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          source: ./
          env_vars: |
            GCS_BUCKET_NAME=caridade

      - name: Show Output URL
        run: echo "App deployada para ${{ steps.deploy.outputs.url }}"
